# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Build & Release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: 
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with: 
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: flutter build appbundle --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}
          commit: main
          tag: v1.0.${{ github.run_number }}

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APPBUNDLE
          path: build/app/outputs/bundle/release/app-release.aab

